pattern:
  - start: 0
    end: 1
    precision: 10
  - start: 0
    end: 2
    precision: 10
  - start: 0
    end: 3
    precision: 10
size: 5
crossoverRate: 0.75
mutationRate: 0.06
elitism: true
maxGen: 100
